config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :event_registrations, only: [ :new, :create, :edit, :update, :destroy ]
  end
  resources :users, only: [ :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "events#index"
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"

  scope :past, -> { where("date < ?", Time.now) }
  scope :upcoming, -> { where("date >= ?", Time.now) }
  enum :availability, { open_to_public: 0, only_private: 1 }

  has_many :attendees, through: :event_registrations, source: :attendee
  has_many :event_registrations, foreign_key: "relevant_event_id", dependent: :destroy

  # def self.past
  # self.where("date < ?", Time.now)
  # end

  # def self.upcoming
  # self.where("date >= ?", Time.now)
  # end
end

app/models/event_registration.rb
class EventRegistration < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :relevant_event, class_name: "Event"

  enum :status, { pending: 0, accepted: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :organized_events, foreign_key: "creator_id", class_name: "Event"
  has_many :attended_events, through: :event_registrations
  has_many :event_registrations, foreign_key: "attendee_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

   before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username ])
  end
end

app/controllers/event_registrations_controller.rb
class EventRegistrationsController < ApplicationController
  before_action :authenticate_user!
  def create
    @event = Event.find(params[:event_id])
    @event_registration = @event.event_registrations.build(reg_params)

    if @event_registration.save
      redirect_to @event
      flash[:notice] = "You have registered."
    else
      flash.now[:alert] = "Something is not right."
      redirect_to @event
    end
  end

  def update
    @event = Event.find(params[:event_id])
    @event_registration = EventRegistration.find_by(attendee: current_user, relevant_event: @event)

    if @event_registration.update(reg_params)
      redirect_to @event
      flash[:notice] = "You have registered."
    else
      flash.now[:alert] = "Something is not right."
      redirect_to @event
    end
  end


  def destroy
    @event = Event.find(params[:event_id])
    @event_registration = @event.event_registrations.find_by(relevant_event_id: params[:event_id], attendee: current_user)

    if @event_registration
      @event_registration.destroy
      redirect_to @event
      flash[:notice] = "You are no longer in attendance."
    else
      flash.now[:alert] = "Something is not right."
      redirect_to @event
    end
  end

  private

  def reg_params
      params.expect(event_registration: [ :attendee_id, :relevant_event_id, :status ])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create ]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @accepted_attendees = User.joins(event_registrations: :relevant_event).where("relevant_event_id = ? AND status = ?", @event, 1)
    @pending_attendees = User.joins(event_registrations: :relevant_event).where("relevant_event_id = ? AND status = ?", @event, 0)
  end

  def create
    @event = current_user.organized_events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def event_params
    params.expect(event: [ :title, :description, :date, :creator, :availability ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_registrations_helper.rb
module EventRegistrationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_registrations/_form.html.erb
<% if @pending_attendees.include?(current_user)%>
       <%  model = [ @event, EventRegistration.find_by(attendee: current_user, relevant_event: @event) ] %>
       <%  method = :patch %>
<% else %>
        <%  model = [ @event, @event.event_registrations.build ] %>
        <%  method = :post %>
<% end %>

<%= form_with model: model, method: method do |form| %>
    <% if @pending_attendees.include?(current_user)%>
        <h2>Accept Invitation?</h2>
        <%= form.hidden_field :status, :value => :accepted %>
    <% else %>
        <h2>Attend?</h2>
        <%= form.hidden_field :status, :value => :accepted %>
        <%= form.hidden_field :attendee_id, :value => current_user.id %>
    <% end %>

        <div>
           <%= form.submit %>
        </div>
<% end %>

app/views/event_registrations/_invitation.html.erb
<h3>Invite?</h3>

<% involved = [@event.creator.id]%>
<% @attendees = User.joins(event_registrations: :relevant_event).where("relevant_event_id = ?", @event) 

@attendees.each do |attendee|
    involved.push(attendee.id) 
end %>

<%= form_with model: [ @event, @event.event_registrations.build ] do |form| %>

        <div>
            <%= form.collection_radio_buttons :attendee_id, User.where.not(id: involved ).order(:username), :id, :username %> 
        </div><br>
    
        <%= form.hidden_field :status, :value => :pending %>

        <div>
           <%= form.submit %>
        </div>
<% end %>

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @event.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% @event.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %><br>
    <% @event.errors.full_messages_for(:date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :availability, value: "Who can see this event?" %><br>
    <%= form.radio_button :availability, :open_to_public %>
    <%= form.label :availability, "Public" %> <br>
    <%= form.radio_button :availability, :only_private %>
    <%= form.label :availability, "Private" %> <br>
    <% @event.errors.full_messages_for(:availability).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event%>

app/views/events/index.html.erb
<%= render "layouts/header" %>

<h1>Most Anticipated Events</h1>

<ul>
    <% @events.upcoming.each do |event| %>
    <% attendees = User.joins(event_registrations: :relevant_event).where("relevant_event_id = ? AND status = ?", event, 1) %>
    <% if event.open_to_public? %>
    <li>
        <%= link_to event.title, event %>
    </li>
    <% else %>
        <% if user_signed_in? && (current_user == event.creator || attendees.include?(current_user))  %>
            <%= link_to event.title, event %>
        <% end %>
    <% end %>
    
    <% end %>
</ul>

<h1>Past Events</h1>

<ul>
    <% @events.past.each do |event| %>
    <% attendees = User.joins(event_registrations: :relevant_event).where("relevant_event_id = ? AND status = ?", event, 1) %>
    
    <% if event.open_to_public? %>
    <li>
        <%= link_to event.title, event %>
    </li>
    <% else %>
        <% if user_signed_in? && (current_user == event.creator || attendees.include?(current_user))  %>
            <%= link_to event.title, event %>
        <% end %>
    <% end %>
    
    <% end %>
</ul>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @event.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% @event.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %><br>
    <% @event.errors.full_messages_for(:date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<%= render "layouts/header" %>

<h1>Title: <%= @event.title %></h1>

<h2>Hosted By <%= link_to @event.creator.username, @event.creator %></h2>

<p>Description: <%= @event.description %></p>

<div>
    <h3>List of Attendees:</h3>
    
    <ul>
        <% @accepted_attendees.each do |attendee| %>
             <li>
                <%= link_to attendee.username, attendee %> <br />
            </li>
        <% end %>
    </ul>
</div>

<!-- _________________________________________________________________________________________________________ -->

<% if user_signed_in? %>
    <% if current_user.id == @event.creator.id %>
        <h3>List of People You Invited:</h3>
    
        <ul>
            <% @pending_attendees.each do |attendee| %>
                <li>
                    <%= link_to attendee.username, attendee %> <br />
                </li>
            <% end %>
        </ul>

        <%= render "event_registrations/invitation", event: @event %>
        
        <ul>
            <li><%= link_to "Edit", edit_event_path(@event) %></li>
            <li><%= link_to "Destroy", event_path(@event), data: {
                                turbo_method: :delete,
                                turbo_confirm: "Are you sure?"
                            } %></li>
        </ul>
    <% else %>
        <% if @accepted_attendees.include?(current_user) == false %>
            <%= render "event_registrations/form", event: @event %>
        <% else %>
            <% event_reg = EventRegistration.where("attendee_id = ? AND relevant_event_id = ?", current_user, @event) %>
            <h3>Leave?</h3>
            <%= button_to "Cancel Attendance", event_event_registration_path(@event, event_reg), method: :delete, data: { turbo_confirm: "Are you sure?" } %>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>

<%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete}%>

<%= link_to "New Event", new_event_path %>

<% else %>

<%= link_to "Sign Up", new_user_registration_path%>

<%= link_to "Sign In", new_user_session_path%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= render "layouts/header" %>

<h1><%= @user.username %></h1>

<div>
    <div>
        <h2>Events Organized</h2>
        <ul>
            <% @user.organized_events.each do |event| %>
            <% attendees = User.joins(event_registrations: :relevant_event).where("relevant_event_id = ?", event) %>
                <% if event.open_to_public? %>
                    <li>
                        <%= link_to event.title, event %>
                    </li>
                    <% else %>
                        <% if user_signed_in? && (current_user == event.creator || attendees.include?(current_user)) %>
                            <li>
                                <%= link_to event.title, event %>
                            </li>
                        <% end %>
                <% end %>
            <% end %>
        </ul>
    </div>
    
    <div>
        <h2>Events Attending</h2>
        <ul>
            <% Event.joins(event_registrations: :attendee).where("date >= ? AND attendee_id = ?", Time.now, @user).each do |event| %>
            <% attendees = User.joins(event_registrations: :relevant_event).where("relevant_event_id = ? AND status = ?", event, 1) %>
                <% if event.open_to_public? %>
                    <li>
                        <%= link_to event.title, event %>
                    </li>
                <% else %>
                        <% if user_signed_in? && (current_user == event.creator || attendees.include?(current_user)) %>
                            <li>
                                <%= link_to event.title, event %>
                            </li>
                        <% end %>
                <% end %>
            <% end %>
        </ul>
    </div>
    
    <div>
        <h2>Events Attended</h2>
        <ul>
            <% Event.joins(event_registrations: :attendee).where("date < ? AND attendee_id = ?", Time.now, @user).each do |event| %>
            <% attendees = User.joins(event_registrations: :relevant_event).where("relevant_event_id = ? AND status = ?", event, 1) %>
                <% if event.open_to_public? %>
                    <li>
                        <%= link_to event.title, event %>
                    </li>
                <% else %>
                        <% if user_signed_in? && (current_user == event.creator || attendees.include?(current_user)) %>
                            <li>
                                <%= link_to event.title, event %>
                            </li>
                        <% end %>
                <% end %>
            <% end %>
        </ul>
    </div>

    
</div>

<% if user_signed_in? && @user = current_user %>
    <div>
        <h2>You have been invited to...</h2>
        <ul>
            <% Event.joins(event_registrations: :attendee).where("date >= ? AND attendee_id = ?", Time.now, @user).each do |event| %>
            <% attendees = User.joins(event_registrations: :relevant_event).where("relevant_event_id = ? AND status = ?", event, 0) %>
                <% if attendees.include?(current_user) %>
                    <li>
                        <%= link_to event.title, event %>
                    </li>
                <% end %>
            <% end %>
        </ul>
    </div>
<% end %>